package com.thefloow.gradle.gitversion;

import com.google.common.io.Files;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Map;

public class VersionFileGenerator {

    private static final Logger L = LoggerFactory.getLogger(VersionFileGenerator.class);

    /**
     * @param gitDir e.g: "/path/to/utilities/.git"
     * @param output e.g: "src/main/resources/META-INF/version/git-${group}_${project.name}.properties"
     * @param version e.g: "1.2.3"
     */
    public void execute(final File gitDir, final File output, final String version) {

        Map<String, String> properties = JGitProvider.gatherProperties(gitDir, version);

        try {

            Files.createParentDirs(output);

            try (OutputStream outputStream = new FileOutputStream(output)) {
                L.info("Writing properties file to [{}]...", output.getAbsolutePath());
                new SortedProperties(properties).store(outputStream, "Generated by gradle-version-plugin");
            }

        } catch (final IOException ex) {
            throw new RuntimeException("Cannot create custom git properties file: " + output.getAbsolutePath(), ex);
        }
    }
}
